barys: Implement v1.1
Signed-off-by: Theodor Gherzan <theodor@resin.io>

diff --git a/scripts/barys b/scripts/barys
--- a/scripts/barys
+++ b/scripts/barys
@@ -14,7 +14,7 @@
 # Signed-off-by: Theodor Gherzan <theodor@resin.io>
 #
 
-BARYSVERSION=1.0
+BARYSVERSION=1.1
 
 # Supported machines - each machine needs an IMAGE_<machine> definition
 SUPPORTED_MACHINES=(raspberrypi raspberrypi2 beaglebone nitrogen6x parallella-hdmi-resin cubox-i)
@@ -37,13 +37,14 @@ BUILDDIR=build
 REMOVEBUILD=no
 COMPRESS=no
 STAGING=no
-SHARED_DOWNLOADS=no
-SHARED_SSTATE=no
+SHARED_DOWNLOADS=
+SHARED_SSTATE=
 DRY_RUN=no
 LOG=no
 LOGFILE=`pwd`/`basename "$0"`.log
 MACHINES=
 BITBAKEARGS=
+EXIT_CODE=0
 
 function help {
     echo "Usage: "`basename "$0"`" [options]"
@@ -90,13 +91,13 @@ function help {
     echo -e "\t\t directory will be removed."
     echo -e "\t\t Default: build."
 
-    echo -e "\t-d | --shared-downloads"
-    echo -e "\t\t Build with shared DL_DIR."
-    echo -e "\t\t Default: no."
+    echo -e "\t--shared-downloads"
+    echo -e "\t\t Use a custom absolute path for DL_DIR."
+    echo -e "\t\t Default: don't have a custom path."
 
     echo -e "\t--shared-sstate"
-    echo -e "\t\t Build with shared SSTATE_DIR."
-    echo -e "\t\t Default: no."
+    echo -e "\t\t Use a custom absolute path for SSTATE_DIR."
+    echo -e "\t\t Default: don't have a custom path."
 
     echo -e "\t-l | --log"
     echo -e "\t\t Log in "`basename "$0"`".log."
@@ -203,11 +204,21 @@ while [[ $# -ge 1 ]]; do
             BUILDDIR=$2
             shift
             ;;
-        -d|--shared-downloads)
-            SHARED_DOWNLOADS=yes
+        --shared-downloads)
+            # Argument needs to be non-empty and absolute path
+            if [ -z "$2" ] || [ "${2:0:1}" != "/" ]; then
+                log ERROR "\"$1\" argument is invalid."
+            fi
+            SHARED_DOWNLOADS=$2
+            shift
             ;;
         --shared-sstate)
-            SHARED_SSTATE=yes
+            # Argument needs to be non-empty and absolute path
+            if [ -z "$2" ] || [ "${2:0:1}" != "/" ]; then
+                log ERROR "\"$1\" argument is invalid."
+            fi
+            SHARED_SSTATE=$2
+            shift
             ;;
         -l|--log)
             LOG=yes
@@ -250,16 +261,29 @@ while [[ $# -ge 1 ]]; do
                 [Yy]* ) REMOVEBUILD=yes;;
             esac
 
-            read -p "Build name? [$BUILDDIR] " $BUILDDIR
+            read -p "Build name? [$BUILDDIR] " yn
+            if [ -n "$yn" ]; then
+                BUILDDIR=$yn
+            fi
 
             read -p "Shared downloads directory? yes/[no] " yn
             case $yn in
-                [Yy]* ) SHARED_DOWNLOADS=yes;;
+                [Yy]* )
+                    read -p "Shared downloads path? " SHARED_DOWNLOADS
+                    if [ -z "$SHARED_DOWNLOADS" ] || [ "${SHARED_DOWNLOADS:0:1}" != "/" ]; then
+                        log ERROR "Provided path is invalid."
+                    fi
+                    ;;
             esac
 
             read -p "Shared sstate directory? yes/[no] " yn
             case $yn in
-                [Yy]* ) SHARED_SSTATE=yes;;
+                [Yy]* )
+                    read -p "Shared sstate path? " SHARED_SSTATE
+                    if [ -z "$SHARED_SSTATE" ] || [ "${SHARED_SSTATE:0:1}" != "/" ]; then
+                        log ERROR "Provided path is invalid."
+                    fi
+                    ;;
             esac
 
             read -p "Generate log? yes/[no] " yn
@@ -297,8 +321,8 @@ if [ "z$LOG" == "zyes" ]; then
     echo "Build directory name: $BUILDDIR" >> $LOGFILE
     echo "Remove build directory? $REMOVEBUILD" >> $LOGFILE
     echo "Compressed image? $COMPRESS" >> $LOGFILE
-    echo "Shared downloads directory? $SHARED_DOWNLOADS" >> $LOGFILE
-    echo "Shared sstate directory? $SHARED_SSTATE" >> $LOGFILE
+    echo "Shared downloads directory: $SHARED_DOWNLOADS" >> $LOGFILE
+    echo "Shared sstate directory: $SHARED_SSTATE" >> $LOGFILE
     echo "Staging builds? $STAGING" >> $LOGFILE
     echo "================"`basename "$0"`" HEADER STOP=====================" >> $LOGFILE
 fi
@@ -329,11 +353,11 @@ fi
 if [ "x$COMPRESS" == "xyes" ]; then
     sed -i "s/.*RESIN_SDIMG_COMPRESSION ?=.*/RESIN_SDIMG_COMPRESSION ?= \"${COMPRESS_TOOL}\"/g" conf/local.conf
 fi
-if [ "x$SHARED_DOWNLOADS" == "xyes" ]; then
-    sed -i "s#.*DL_DIR ?=.*#DL_DIR ?= \"$SCRIPTPATH/../shared-downloads\"#g" conf/local.conf
+if [ -n "$SHARED_DOWNLOADS" ]; then
+    sed -i "s#.*DL_DIR ?=.*#DL_DIR ?= \"$SHARED_DOWNLOADS\"#g" conf/local.conf
 fi
-if [ "x$SHARED_SSTATE" == "xyes" ]; then
-    sed -i "s#.*SSTATE_DIR ?=.*#SSTATE_DIR ?= \"$SCRIPTPATH/../shared-sstate\"#g" conf/local.conf
+if [ -n "$SHARED_SSTATE" ]; then
+    sed -i "s#.*SSTATE_DIR ?=.*#SSTATE_DIR ?= \"$SHARED_SSTATE\"#g" conf/local.conf
 fi
 log "Resin build initialized in $BUILDDIR."
 
@@ -359,6 +383,7 @@ else
           log "Build for $machine suceeded."
       else
           log "Build for $machine failed. Check failed log in $BUILDDIR/tmp/log/cooker/$machine ."
+          EXIT_CODE=2 # Fail at the end
       fi
   done
   for machine in $ITERATOR_MACHINES; do
@@ -372,4 +397,4 @@ fi
 log "Done."
 echo "===================="`basename "$0"`" STOP========================" >> $LOGFILE
 
-exit 0
+exit $EXIT_CODE
