barys: Implement json boards description
Signed-off-by: Theodor Gherzan <theodor@resin.io>

diff --git a/scripts/barys b/scripts/barys
--- a/scripts/barys
+++ b/scripts/barys
@@ -16,20 +16,8 @@
 
 BARYSVERSION=1.1
 
-# Supported machines - each machine needs an IMAGE_<machine> definition
-SUPPORTED_MACHINES=(raspberrypi raspberrypi2 beaglebone nitrogen6x parallella-hdmi-resin cubox-i)
-IMAGE_raspberrypi=resin-image
-IMAGE_raspberrypi2=resin-image
-IMAGE_beaglebone=resin-image-flasher
-IMAGE_nitrogen6x=resin-image
-IMAGE_parallella_hdmi_resin=resin-image
-IMAGE_cubox_i=resin-image
-FSTYPE_raspberrypi=resin-sdcard
-FSTYPE_raspberrypi2=resin-sdcard
-FSTYPE_beaglebone=resin-sdcard
-FSTYPE_nitrogen6x=resin-sdcard
-FSTYPE_parallella_hdmi_resin=resin-sdcard
-FSTYPE_cubox_i=resin-sdcard
+# JSON machine desciption file
+JSON=resin-boards.json
 
 # Default values
 COMPRESS_TOOL="xz"
@@ -58,7 +46,7 @@ function help {
     echo -e "\t-m | --machine"
     echo -e "\t\t Build a supported machine."
     echo -e "\t\t Supported machines:"
-    for m in ${SUPPORTED_MACHINES[@]}; do
+    for m in ${SUPPORTED_MACHINES}; do
         echo -e "\t\t\t $m"
     done
     echo -e "\t\t Default: build all supported machines."
@@ -151,7 +139,7 @@ function log {
 
 function check_machine {
     found=0
-    for mi in "${SUPPORTED_MACHINES[@]}"; do
+    for mi in ${SUPPORTED_MACHINES}; do
         if [ "$1" == "$mi" ]; then
             found=1
             break
@@ -166,6 +154,17 @@ STARTTIME=$(date +%s)
 pushd `dirname $0` > /dev/null 2>&1
 SCRIPTPATH=`pwd`
 popd > /dev/null 2>&1
+
+if [ ! -f $SCRIPTPATH/$JSON ]; then
+    log ERROR "Cannot find $JSON file in $SCRIPTPATH."
+else
+    SUPPORTED_MACHINES=`cat $SCRIPTPATH/$JSON | jq  -r '.supported[].machine'`
+fi
+
+# This script depends on jq
+if ! `which jq > /dev/null 2>&1`; then
+    log ERROR "jq dependency failed. Make sure you have jq installed on your system."
+fi
 
 # Backup $@
 SCRIPT_ARGUMENTS=$@
@@ -236,8 +235,8 @@ while [[ $# -ge 1 ]]; do
             ;;
         -i|--interactive)
             echo -n "Supported machines:"
-            for m in ${SUPPORTED_MACHINES[@]}; do
-                echo -n "$m "
+            for m in ${SUPPORTED_MACHINES}; do
+                echo -n " $m"
             done
             echo "."
             read -p "Select machines. Space separated or empty for all: " m
@@ -359,6 +358,7 @@ fi
 cd $SCRIPTPATH/..
 
 # Configure build
+$SCRIPTPATH/generate-conf-notes.sh $SCRIPTPATH/../meta-resin/meta-resin-common/conf $SCRIPTPATH/$JSON
 export TEMPLATECONF=../meta-resin/meta-resin-common/conf/
 source poky/oe-init-build-env $BUILDDIR
 if [ "x$STAGING" == "xyes" ]; then
@@ -384,18 +384,18 @@ if [ "$DRY_RUN" == "yes" ]; then
   log WARN "Don't forget to setup build MACHINE as this script ignores it in dry run mode."
 else
   if [ -z "$MACHINES" ]; then
-      ITERATOR_MACHINES="${SUPPORTED_MACHINES[@]}"
+      ITERATOR_MACHINES="${SUPPORTED_MACHINES}"
   else
       ITERATOR_MACHINES="$MACHINES"
   fi
   for machine in $ITERATOR_MACHINES; do
-      IMAGE_VAR=`echo "IMAGE_$machine" | sed 's/-/_/g'`
-      if [ -z "${!IMAGE_VAR}" ]; then
+      IMAGE=`cat $SCRIPTPATH/$JSON | jq  -r '.supported[] | select(.machine == '\"${machine}\"').image'`
+      if [ -z "$IMAGE" ] || [ "z$IMAGE" == "znull" ]; then
           log ERROR "No target image defined for $machine."
       fi
-      log "Run build for $machine: MACHINE=$machine bitbake ${!IMAGE_VAR} $BITBAKEARGS"
+      log "Run build for $machine: MACHINE=$machine bitbake $IMAGE $BITBAKEARGS"
       log "This might take a while ..."
-      env MACHINE=$machine bitbake ${!IMAGE_VAR} $BITBAKEARGS
+      env MACHINE=$machine bitbake ${IMAGE} $BITBAKEARGS
       if [ $? -eq 0 ]; then
           log "Build for $machine suceeded."
       else
@@ -404,10 +404,13 @@ else
       fi
   done
   for machine in $ITERATOR_MACHINES; do
-        IMAGE_VAR=`echo "IMAGE_$machine" | sed 's/-/_/g'`
-        FSTYPE_VAR=`echo "FSTYPE_$machine" | sed 's/-/_/g'`
+        IMAGE=`cat $SCRIPTPATH/$JSON | jq  -r '.supported[] | select(.machine == '\"${machine}\"').image'`
+        FSTYPE=`cat $SCRIPTPATH/$JSON | jq  -r '.supported[] | select(.machine == '\"${machine}\"').fstype'`
+        if [ -z "$IMAGE" ] || [ -z "$FSTYPE" ] || [ "z$IMAGE" == "znull" ] || [ "z$FSTYPE" == "znull" ]; then
+          log ERROR "No target image and/or fstype defined for $machine."
+      fi
         log "If build for $machine succeeded, final image should have been generated here:"
-        log "   $BUILDDIR/tmp/deploy/images/$machine/${!IMAGE_VAR}-$machine.${!FSTYPE_VAR}"
+        log "   $BUILDDIR/tmp/deploy/images/$machine/$IMAGE-$machine.$FSTYPE"
   done
 fi
 
